name: CI
on:
  push:

env:
    DEVELOPER_DIR: /Applications/Xcode_13.0.app
jobs:
  Deploy:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: xcodebuild clean test 
          -scheme <scheme_name> -sdk iphonesimulator
          -destination 'platform=iOS Simulator,name=iPhone 13'
