name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#jobs:
#  build:
#
#    runs-on: macos-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Install Dependencies
#      run: |
#       pod install --repo-update
#    - name: Run tests
#      run: xcodebuild clean test
#        -scheme $default -sdk iphonesimulator
#        -destination 'platform=iOS Simulator,name=iPhone 13'
jobs:
  unit_tests:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - name: Force Xcode 12
      run: sudo xcode-select -switch /Applications/Xcode_12.app
#     - name: Build
#       run: swift build -v
#     - name: Run tests
#       run: swift test -v
    - name: Build and test
      run: xcodebuild clean build test -workspace App/IOSEX.xcworkspace -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

#        -scheme $default -sdk iphonesimulator
