name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#jobs:
#  build:
#
#    runs-on: macos-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Install Dependencies
#      run: |
#       pod install --repo-update
#    - name: Run tests
#      run: xcodebuild clean test
#        -scheme $default -sdk iphonesimulator
#        -destination 'platform=iOS Simulator,name=iPhone 13'
jobs:
  unit_tests:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.1.app/Contents/Developer
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build
    - name: Run tests 
      run: swift test
