name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#jobs:
#  build:
#
#    runs-on: macos-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Install Dependencies
#      run: |
#       pod install --repo-update
#    - name: Run tests
#      run: xcodebuild clean test
#        -scheme $default -sdk iphonesimulator
#        -destination 'platform=iOS Simulator,name=iPhone 13'
jobs:
  unit_tests:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - name: Force Xcode 12
      run: sudo xcode-select -switch /Applications/Xcode_12.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: iOS build setup
<<<<<<< HEAD
        run: >-
          xcodebuild test -workspace IOSEX.xcodeproj/project.xcworkspace
          -scheme IOSEX -destination 'platform=iOS Simulator,name=iPhone
          11,OS=13.7'
      - name: testing ... iPhone 11
        run: >-
          xcodebuild test -workspace IOSEX.xcodeproj/project.xcworkspace
          -scheme IOSEX -destination 'platform=iOS Simulator,name=iPhone
          11,OS=13.7'
      - name: testing ... iPhone 11 Pro Max
        run: >-
          xcodebuild test -workspace IOSEX.xcodeproj/project.xcworkspace
          -scheme IOSEX -destination 'platform=iOS Simulator,name=iPhone 11
          Pro Max,OS=13.7'
      - name: testing ... iPad Air
        run: >-
          xcodebuild test -workspace IOSEX.xcodeproj/project.xcworkspace
          -scheme IOSEX -destination 'platform=iOS Simulator,name=iPad Air
          (3rd generation),OS=13.7'
      - name: testing ... iPad Pro 12.9
        run: >-
          xcodebuild test -workspace IOSEX.xcodeproj/project.xcworkspace
          -scheme IOSEX -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (4th generation),OS=13.7'
=======
      run: |
          xcodebuild test -workspace IOSEX.xcodeproj/project.xcworkspace
          -scheme IOSEX -destination 'platform=iOS Simulator,name=iPhone
          11,OS=13.7'
    - name: testing ... iPhone 11
      run: |
        xcodebuild test -workspace IOSEX.xcodeproj/project.xcworkspace
        -scheme IOSEX -destination 'platform=iOS Simulator,name=iPhone
        11,OS=13.7'
    - name: testing ... iPhone 11 Pro Max
      run: |
        xcodebuild test -workspace IOSEX.xcodeproj/project.xcworkspace
        -scheme IOSEX -destination 'platform=iOS Simulator,name=iPhone 11
        Pro Max,OS=13.7'
    - name: testing ... iPad Air
      run: |
        xcodebuild test -workspace IOSEX.xcodeproj/project.xcworkspace
        -scheme IOSEX -destination 'platform=iOS Simulator,name=iPad Air
        (3rd generation),OS=13.7'
    - name: testing ... iPad Pro 12.9
      run: |
        xcodebuild test -workspace IOSEX.xcodeproj/project.xcworkspace
        -scheme IOSEX -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (4th generation),OS=13.7'
>>>>>>> 430b9828b09432fbe46adbfaf4a681c7a00dd2a2
